/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package clases;

import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USUARIO
 */
public class AdoptarGato extends javax.swing.JInternalFrame {

    List<Animal> listaAnimales;

    OperacionesVisual obj;
    //get and set

    public OperacionesVisual getObj() {
        return obj;
    }

    public void setObj(OperacionesVisual obj) {
        this.obj = obj;
    }

    /**
     * Creates new form AdoptarPerro
     */
    public AdoptarGato() {
        initComponents();
    }

    public void mostrarGatosDisponibles() {
        int f = 0;
        listaAnimales = obj.getListaAnimales();
        DefaultTableModel modelo = (DefaultTableModel) tablaPerrosDispo.getModel();
        modelo.setColumnCount(5); // Columnas: Nro, ID, Nombre, Edad, Raza
        modelo.setRowCount(0); // Limpiar filas anteriores

        if (listaAnimales != null && !listaAnimales.isEmpty()) {
            for (Animal animal : listaAnimales) {
                if (animal instanceof Gato && animal.isDisponible()) {
                    modelo.setRowCount(f + 1);
                    Gato g = (Gato) animal;

                    tablaPerrosDispo.setValueAt(f + 1, f, 0);
                    tablaPerrosDispo.setValueAt(g.getId(), f, 1);
                    tablaPerrosDispo.setValueAt(g.getNombre(), f, 2);
                    tablaPerrosDispo.setValueAt(g.getEdad(), f, 3);
                    f++;
                }
            }
        }

        if (f == 0) {
            msjLbl.setText("NO HAY GATOS DISPONIBLES EN ESTE MOMENTO");
            msjLbl.setForeground(java.awt.Color.red);
        } else {
            msjLbl.setText("");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDniAdoptante = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPerrosDispo = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txtIdAnimal = new javax.swing.JTextField();
        btnAdoptar = new javax.swing.JButton();
        msjLbl = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLabel1.setText("ADOPTAR UN GATO");

        jLabel2.setText("CI: ");

        tablaPerrosDispo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "N°", "ID", "NOMBRE", "EDAD"
            }
        ));
        jScrollPane1.setViewportView(tablaPerrosDispo);

        jLabel3.setText("ID:");

        txtIdAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdAnimalActionPerformed(evt);
            }
        });

        btnAdoptar.setText("ADOPTAR");
        btnAdoptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdoptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(txtIdAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAdoptar)
                .addGap(118, 118, 118))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel2)
                        .addGap(35, 35, 35)
                        .addComponent(txtDniAdoptante, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(msjLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDniAdoptante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtIdAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdoptar))
                .addGap(18, 18, 18)
                .addComponent(msjLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdAnimalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdAnimalActionPerformed

    private void btnAdoptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdoptarActionPerformed
        String dni = txtDniAdoptante.getText().trim();
        String idAnimal = txtIdAnimal.getText().trim();

        if (dni.isEmpty() || idAnimal.isEmpty()) {
            msjLbl.setText("POR FAVOR, INGRESE AMBOS CAMPOS (DNI E ID)");
            msjLbl.setForeground(java.awt.Color.red);
            return;
        }

        // 1. Verificar si el adoptante existe
        Adoptante adoptanteEncontrado = obj.buscarAdoptantePorDni(dni);

        // 2. Verificar si el animal existe
        Animal animalEncontrado = obj.buscarAnimalPorId(idAnimal);

        if (adoptanteEncontrado == null) {
            msjLbl.setText("EL DNI DEL ADOPTANTE NO ESTÁ REGISTRADO");
            msjLbl.setForeground(java.awt.Color.red);
        } else if (animalEncontrado == null || !(animalEncontrado instanceof Gato)) {
            msjLbl.setText("EL ID DEL GATO NO EXISTE O NO ES VALIDO");
            msjLbl.setForeground(java.awt.Color.red);
        } else {
            if (!animalEncontrado.isDisponible()) {
                msjLbl.setText("ESTE ANIMAL YA FUE ADOPTADO ANTERIORMENTE");
                msjLbl.setForeground(java.awt.Color.red);
                return;
            }

            adoptanteEncontrado.getAnimalesAdoptados().add(animalEncontrado);


            animalEncontrado.setDisponible(false);


            javax.swing.JOptionPane.showMessageDialog(this,
                    "¡ADOPCIÓN EXITOSA!\nEl perro " + animalEncontrado.getNombre()
                    + " ahora pertenece a la lista de " + adoptanteEncontrado.getNombre());

            // 4. Limpiar componentes y refrescar la tabla
            txtDniAdoptante.setText("");
            txtIdAnimal.setText("");
            msjLbl.setText("");
            mostrarGatosDisponibles();
        }
    }//GEN-LAST:event_btnAdoptarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdoptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel msjLbl;
    private javax.swing.JTable tablaPerrosDispo;
    private javax.swing.JTextField txtDniAdoptante;
    private javax.swing.JTextField txtIdAnimal;
    // End of variables declaration//GEN-END:variables
}
