/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package clases;

import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USUARIO
 */
public class GestionarRevisionPerro extends javax.swing.JInternalFrame {

    OperacionesVisual obj;
    //get and set

    public OperacionesVisual getObj() {
        return obj;
    }

    public void setObj(OperacionesVisual obj) {
        this.obj = obj;
    }

    /**
     * Creates new form GestionarRevision
     */
    public GestionarRevisionPerro() {
        initComponents();
    }

    
    

    public void mostrarPerros() {
        int f = 0;
        List<Animal> lista = obj.getListaAnimales();
        DefaultTableModel modelo = (DefaultTableModel) tablaPerrosMedicos.getModel();
        modelo.setColumnCount(6); // Nro, ID, Nombre, Edad, Estado Salud, Disponible
        modelo.setRowCount(0);

        if (lista != null && !lista.isEmpty()) {
            for (Animal a : lista) {
                if (a instanceof Perro) {
                    modelo.setRowCount(f + 1);
                    Perro p = (Perro) a;
                    tablaPerrosMedicos.setValueAt(f + 1, f, 0);
                    tablaPerrosMedicos.setValueAt(p.getId(), f, 1);
                    tablaPerrosMedicos.setValueAt(p.getNombre(), f, 2);
                    tablaPerrosMedicos.setValueAt(p.getEdad(), f, 3);
                    tablaPerrosMedicos.setValueAt(p.getEstadoSalud(), f, 4);
                    tablaPerrosMedicos.setValueAt(p.isDisponible() ? "Sí" : "No", f, 5);
                    f++;
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPerrosMedicos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtIdBuscar = new javax.swing.JTextField();
        cmbNuevoEstado = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        msjLbl = new javax.swing.JLabel();
        btnRegistrarRevision = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLabel1.setText("GESTIONAR REVISION PERRO");

        tablaPerrosMedicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "N°", "ID", "NOMBRE", "EDAD", "SALUD", "ADOPTABLE"
            }
        ));
        jScrollPane1.setViewportView(tablaPerrosMedicos);

        jLabel2.setText("ID:");

        cmbNuevoEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Saludable", "En tratamiento", "Critico", "En Observacion" }));

        jLabel3.setText("NUEVO DIAGNOSTICO: ");

        btnRegistrarRevision.setText("REVISION");
        btnRegistrarRevision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarRevisionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtIdBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnRegistrarRevision)
                                    .addComponent(jLabel3))
                                .addGap(38, 38, 38)
                                .addComponent(cmbNuevoEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(msjLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(msjLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIdBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbNuevoEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(55, 55, 55)
                .addComponent(btnRegistrarRevision)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarRevisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarRevisionActionPerformed
        // Captura el ID digitado manualmente
        String idDigitado = txtIdBuscar.getText().trim();
        String nuevoEstado = cmbNuevoEstado.getSelectedItem().toString();

        if (idDigitado.isEmpty()) {
            msjLbl.setText("POR FAVOR, DIGITE EL ID DEL PERRO");
            msjLbl.setForeground(java.awt.Color.red);
            return;
        }

        // Buscamos primero si el animal existe y realmente es un Perro
        Animal animal = obj.buscarAnimalPorId(idDigitado);

        if (animal == null || !(animal instanceof Perro)) {
            msjLbl.setText("EL ID DIGITADO NO CORRESPONDE A NINGÚN PERRO REGISTRADO");
            msjLbl.setForeground(java.awt.Color.red);
            return;
        }

        // Procesamos la revisión médica con la nueva regla
        boolean exito = obj.procesarRevisionMedica(idDigitado, nuevoEstado);

        if (exito) {
            String mensaje = "Revisión registrada para el perro: " + animal.getNombre() + "\nSalud: " + nuevoEstado;
            if (nuevoEstado.equalsIgnoreCase("Saludable")) {
                mensaje += "\n¡El perro ahora vuelve a estar DISPONIBLE para adopción!";
            }

            javax.swing.JOptionPane.showMessageDialog(this, mensaje);

            // Limpiamos el campo digitado y refrescamos la tabla
            txtIdBuscar.setText("");
            cmbNuevoEstado.setSelectedIndex(0);
            msjLbl.setText("");
            mostrarPerros();
        }
    }//GEN-LAST:event_btnRegistrarRevisionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarRevision;
    private javax.swing.JComboBox<String> cmbNuevoEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel msjLbl;
    private javax.swing.JTable tablaPerrosMedicos;
    private javax.swing.JTextField txtIdBuscar;
    // End of variables declaration//GEN-END:variables
}
