/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package clases;

import java.awt.Color;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USUARIO
 */
public class MostrarPerros extends javax.swing.JInternalFrame {
    List<Animal> listaAnimales;
    
    OperacionesVisual obj;
    //get and set

    public OperacionesVisual getObj() {
        return obj;
    }

    public void setObj(OperacionesVisual obj) {
        this.obj = obj;
    }

    /**
     * Creates new form MostrarPerros
     */
    public MostrarPerros() {
        initComponents();
    }
    
    public void mostrarDatos() {
    int f = 0;
    // Capturamos la lista general de animales desde tu objeto de operaciones
    listaAnimales = obj.getListaAnimales();
    
    if (listaAnimales != null && !listaAnimales.isEmpty()) {
        DefaultTableModel modelo = (DefaultTableModel) tablaPerroTbl.getModel();

        modelo.setColumnCount(8); 
        
        modelo.setRowCount(listaAnimales.size()); 
        
        // Llenando los datos a la tabla con filtrado polimórfico
        for (Animal animal : listaAnimales) {
            // Como la lista tiene tanto perros como gatos, filtramos para mostrar SOLO perros
            if (animal instanceof Perro) {
                Perro p = (Perro) animal; // Conversión (Cast) a Perro para acceder a sus atributos únicos
                
                tablaPerroTbl.setValueAt(f + 1, f, 0);               // Nro correlativo
                tablaPerroTbl.setValueAt(p.getId(), f, 1);           // Atributo de Animal
                tablaPerroTbl.setValueAt(p.getNombre(), f, 2);       // Atributo de Animal                            
                tablaPerroTbl.setValueAt(p.getEdad(), f, 3);         // Atributo de Animal
                tablaPerroTbl.setValueAt(p.getRaza(), f, 4);         // Atributo específico de Perro
                tablaPerroTbl.setValueAt(p.getTamaño(), f, 5);       // Atributo específico de Perro
                tablaPerroTbl.setValueAt(p.getEstadoSalud(), f, 6);  // Atributo de Animal
                
                // Formato visual para el booleano de disponibilidad
                String disponibleTxt = p.isDisponible() ? "Sí" : "No";
                tablaPerroTbl.setValueAt(disponibleTxt, f, 7);
                
                
                f++;
            }
        }
        
        // Si después de recorrer la lista no se sumó ningún perro
        if (f == 0) {
            msjLbl.setText("NO SE TIENE NINGÚN PERRO REGISTRADO");
            msjLbl.setForeground(Color.red);
            modelo.setRowCount(0); // Vacía la tabla visualmente
        } else {
            msjLbl.setText(""); // Limpia mensajes anteriores si hay datos
            modelo.setRowCount(f); // Ajusta las filas exactamente a la cantidad de perros encontrados
        }
        
    } else {
        msjLbl.setText("NO SE TIENE NINGÚN ANIMAL REGISTRADO");
        msjLbl.setForeground(Color.red);
        
        // Limpiamos la tabla visualmente
        DefaultTableModel modelo = (DefaultTableModel) tablaPerroTbl.getModel();
        modelo.setRowCount(0);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        msjLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPerroTbl = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLabel1.setText("LISTA DE PERROS REGISTRADOS");

        tablaPerroTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "N°", "ID", "NOMBRE", "EDAD", "RAZA", "TAMAÑO", "ESTADO", "ADOPTABLE"
            }
        ));
        jScrollPane1.setViewportView(tablaPerroTbl);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(msjLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(msjLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel msjLbl;
    private javax.swing.JTable tablaPerroTbl;
    // End of variables declaration//GEN-END:variables
}
