/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package clases;

import java.awt.Color;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USUARIO
 */
public class MostrarAdoptante extends javax.swing.JInternalFrame {
    List<Adoptante> listaAdoptantes;
    
    OperacionesVisual obj;
    //get and set

    public OperacionesVisual getObj() {
        return obj;
    }

    public void setObj(OperacionesVisual obj) {
        this.obj = obj;
    }

    /**
     * Creates new form MostrarPerros
     */
    public MostrarAdoptante() {
        initComponents();
    }
    
   public void mostrarDatos() {
    int f = 0;
    // Capturamos la lista específica de adoptantes
    listaAdoptantes = obj.getListaAdoptantes();
    
    if (listaAdoptantes != null && !listaAdoptantes.isEmpty()) {
        DefaultTableModel modelo = (DefaultTableModel) tablaAdoptanteTbl.getModel();
        
        // Columnas: Nro, DNI, Nombre Completo, Teléfono
        modelo.setColumnCount(4);
        modelo.setRowCount(listaAdoptantes.size());
        
        // Recorremos y llenamos directamente la tabla
        for (Adoptante ad : listaAdoptantes) {
            tablaAdoptanteTbl.setValueAt(f + 1, f, 0);          // Nro
            tablaAdoptanteTbl.setValueAt(ad.getDni(), f, 1);    // DNI
            tablaAdoptanteTbl.setValueAt(ad.getNombre(), f, 2); // Nombre
            tablaAdoptanteTbl.setValueAt(ad.getTelefono(), f, 3); // Teléfono
            f++;
        }
        
        msjLbl.setText(""); // Limpia cualquier advertencia previa
        modelo.setRowCount(f);
        
    } else {
        msjLbl.setText("NO SE TIENE NINGÚN ADOPTANTE REGISTRADO");
        msjLbl.setForeground(Color.red);
        
        DefaultTableModel modelo = (DefaultTableModel) tablaAdoptanteTbl.getModel();
        modelo.setRowCount(0); // Vacía la tabla si no hay datos
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        msjLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaAdoptanteTbl = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLabel1.setText("LISTA DE PERROS REGISTRADOS");

        tablaAdoptanteTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "N°", "CI", "NOMBRE", "TELEFONO"
            }
        ));
        jScrollPane1.setViewportView(tablaAdoptanteTbl);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(msjLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(msjLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel msjLbl;
    private javax.swing.JTable tablaAdoptanteTbl;
    // End of variables declaration//GEN-END:variables
}
