/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clases;

/**
 *
 * @author USUARIO
 */
public class Refugio extends javax.swing.JFrame {

    OperacionesVisual op;

    /**
     * Creates new form Veterinaria
     */
    public Refugio() {
        initComponents();
        op = new OperacionesVisual();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        RegistrarPerro = new javax.swing.JMenuItem();
        MostrarPerro = new javax.swing.JMenuItem();
        adoptarPerro = new javax.swing.JMenuItem();
        revisionPerro = new javax.swing.JMenuItem();
        MostrarGato = new javax.swing.JMenu();
        registrarGato = new javax.swing.JMenuItem();
        mostrarGato = new javax.swing.JMenuItem();
        adoptarGato = new javax.swing.JMenuItem();
        revisionGato = new javax.swing.JMenuItem();
        MostrarAdop = new javax.swing.JMenu();
        registrarAdop = new javax.swing.JMenuItem();
        mostrarAdop = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 366, Short.MAX_VALUE)
        );

        jMenu1.setText("Perro");

        RegistrarPerro.setText("Registrar");
        RegistrarPerro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarPerroActionPerformed(evt);
            }
        });
        jMenu1.add(RegistrarPerro);

        MostrarPerro.setText("Mostrar");
        MostrarPerro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarPerroActionPerformed(evt);
            }
        });
        jMenu1.add(MostrarPerro);

        adoptarPerro.setText("Adoptar");
        adoptarPerro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adoptarPerroActionPerformed(evt);
            }
        });
        jMenu1.add(adoptarPerro);

        revisionPerro.setText("Revision");
        revisionPerro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                revisionPerroActionPerformed(evt);
            }
        });
        jMenu1.add(revisionPerro);

        jMenuBar1.add(jMenu1);

        MostrarGato.setText("Gato");

        registrarGato.setText("Registrar");
        registrarGato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarGatoActionPerformed(evt);
            }
        });
        MostrarGato.add(registrarGato);

        mostrarGato.setText("Mostrar");
        mostrarGato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarGatoActionPerformed(evt);
            }
        });
        MostrarGato.add(mostrarGato);

        adoptarGato.setText("Adoptar");
        adoptarGato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adoptarGatoActionPerformed(evt);
            }
        });
        MostrarGato.add(adoptarGato);

        revisionGato.setText("Revision");
        revisionGato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                revisionGatoActionPerformed(evt);
            }
        });
        MostrarGato.add(revisionGato);

        jMenuBar1.add(MostrarGato);

        MostrarAdop.setText("Adoptante");

        registrarAdop.setText("Registrar");
        registrarAdop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarAdopActionPerformed(evt);
            }
        });
        MostrarAdop.add(registrarAdop);

        mostrarAdop.setText("Mostrar");
        mostrarAdop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarAdopActionPerformed(evt);
            }
        });
        MostrarAdop.add(mostrarAdop);

        jMenuBar1.add(MostrarAdop);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegistrarPerroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarPerroActionPerformed
        RegistrarPerro registrar = new RegistrarPerro();
        registrar.setObj(op);
        escritorio.add(registrar);
        registrar.show();
    }//GEN-LAST:event_RegistrarPerroActionPerformed

    private void registrarGatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarGatoActionPerformed
        RegistrarGato registrar = new RegistrarGato();
        registrar.setObj(op);
        escritorio.add(registrar);
        registrar.show();// TODO add your handling code here:
    }//GEN-LAST:event_registrarGatoActionPerformed

    private void registrarAdopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarAdopActionPerformed
        RegistrarAdoptante registrar = new RegistrarAdoptante();
        registrar.setObj(op);
        escritorio.add(registrar);
        registrar.show();
    }//GEN-LAST:event_registrarAdopActionPerformed

    private void MostrarPerroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarPerroActionPerformed
        MostrarPerros mostrar = new MostrarPerros();
        mostrar.setObj(op);
        //llamando al metodo
        mostrar.mostrarDatos();
        escritorio.add(mostrar);
        mostrar.show();
    }//GEN-LAST:event_MostrarPerroActionPerformed

    private void mostrarGatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarGatoActionPerformed
        MostrarGatos mostrar = new MostrarGatos();
        mostrar.setObj(op);
        //llamando al metodo
        mostrar.mostrarDatos();
        escritorio.add(mostrar);
        mostrar.show();
    }//GEN-LAST:event_mostrarGatoActionPerformed

    private void mostrarAdopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarAdopActionPerformed
        MostrarAdoptante mostrar = new MostrarAdoptante();
        mostrar.setObj(op);
        //llamando al metodo
        mostrar.mostrarDatos();
        escritorio.add(mostrar);
        mostrar.show();
    }//GEN-LAST:event_mostrarAdopActionPerformed

    private void adoptarPerroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adoptarPerroActionPerformed
        AdoptarPerro adoptar = new AdoptarPerro();
        adoptar.setObj(op);
        //llamando al metodo
        adoptar.mostrarPerrosDisponibles();
        escritorio.add(adoptar);
        adoptar.show();
    }//GEN-LAST:event_adoptarPerroActionPerformed

    private void adoptarGatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adoptarGatoActionPerformed
        AdoptarGato adoptar = new AdoptarGato();
        adoptar.setObj(op);
        adoptar.mostrarGatosDisponibles();
        escritorio.add(adoptar);
        adoptar.show();
    }//GEN-LAST:event_adoptarGatoActionPerformed

    private void revisionPerroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_revisionPerroActionPerformed
        GestionarRevisionPerro revision = new GestionarRevisionPerro();
        revision.setObj(op);
        revision.mostrarPerros();
        escritorio.add(revision);
        revision.show();
    }//GEN-LAST:event_revisionPerroActionPerformed

    private void revisionGatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_revisionGatoActionPerformed
        GestionarRevisionGato revision = new GestionarRevisionGato();
        revision.setObj(op);
        revision.mostrarGatos();
        escritorio.add(revision);
        revision.show();
    }//GEN-LAST:event_revisionGatoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Refugio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Refugio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Refugio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Refugio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Refugio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MostrarAdop;
    private javax.swing.JMenu MostrarGato;
    private javax.swing.JMenuItem MostrarPerro;
    private javax.swing.JMenuItem RegistrarPerro;
    private javax.swing.JMenuItem adoptarGato;
    private javax.swing.JMenuItem adoptarPerro;
    private javax.swing.JPanel escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mostrarAdop;
    private javax.swing.JMenuItem mostrarGato;
    private javax.swing.JMenuItem registrarAdop;
    private javax.swing.JMenuItem registrarGato;
    private javax.swing.JMenuItem revisionGato;
    private javax.swing.JMenuItem revisionPerro;
    // End of variables declaration//GEN-END:variables
}
